# ci.yml

name: Release Mua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

# permissions:
#  contents: read

jobs:
  tmate:
    name: Action tmate session
    runs-on: macos-latest
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
      timeout-minutes: 15
  make-linux:
    name: Build Mua - Linux
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch'}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: make muac
      working-directory: .
      run: make -j SYS=Linux #-f ./make/mua/token.mk
    - name: Upload muac-linux
      uses: actions/upload-artifact@v4
      with:
        name: muac-linux
        path: build/mua/main/muac
  make-windows:
    name: Build Mua - Windows
    runs-on: windows-latest
    if: ${{ github.event_name != 'workflow_dispatch'}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: make muac
      shell: pwsh
      working-directory: .
      run: make -j SYS=Linux
    - name: Upload muac-windows
      uses: actions/upload-artifact@v4
      with:
        name: muac-windows
        path: build/mua/main/muac.exe
  make-macos:
    name: Build Mua - MacOS
    runs-on: macos-latest
    if: ${{ github.event_name != 'workflow_dispatch'}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: make muac
      working-directory: .
      run: |
        make -j SYS=OSX CXX_VERSION=c++20
    - name: Upload muac-macos
      uses: actions/upload-artifact@v4
      with:
        name: muac-macos
        path: build/mua/main/muac
  release-mua:
    name: Create Mua release
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch'}}
    needs: [make-linux, make-windows, make-macos]
    steps:
    - name: Download Mua artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded artifacts
      run: ls -R

