# tests.yml

name: STEM Tests

on: [push, pull_request]

# permissions:
#  contents: read

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

  # token_test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: print premake path
  #     working-directory: ./premake
  #     run : |
  #       chmod a+x premake5
  #       ./premake5 --help