# tests.yml

name: STEM Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

# permissions:
#  contents: read

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
      timeout-minutes: 15

  token_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print premake path
      working-directory: ./premake
      run : |
        chmod a+x ./premake5
        ./premake5 build --stem=token
        ./premake5 build --stemT=TokenUtils
        cd ../build/stem-test/TokenUtilsTest
        ./TokenUtilsTest